### PR TITLE
Update german translation (add missing translations)

### PR DESCRIPTION
**Pull request by Trojaner25**
Seems like some newer translation messages weren't updated

### CODE REVIEW

**Comment by sgdc3** [comment]
CLose this and post in at https://github.com/AuthMe-Team/AuthMeReloaded

**Comment by sgdc3** [comment]
@irobin591 We need translators, do you want to be our DE translator? :)

**Comment by irobin591** [comment]
I could try that, but my english isn't really good. :)

**Comment by sgdc3** [comment]
Fixed everything on the AuthMe-Team fork :) Also sent a new PR, @Trojaner25 please close this.

**Comment by sgdc3** [comment]
@Xephi Don't merge this PR, just look the AuthMe-Team one :)

**Pull request closed without merging**
