### PR TITLE
Fixed some maven issues + enabled Travis cache

### PR DESCRIPTION
**Pull request by sgdc3**
There are still too many repositories, we need to find a way to reduce their number and exclude slow repos.

### CODE REVIEW

**Comment by Kongolan** [comment]
Remove Spout support for Authme 5.0? It's discontinued and stuck on 1.6.somewhere anyways. Or is Authme 5.0 actually downwards compatible?

**Comment by sgdc3** [comment]
I know, I tell Xephi about that...

**Comment by sgdc3** [comment]
I'm not a Java developer, can you create a P.R. which removes Spout and old xAuth integrations? :)

**Comment by Xephi** [comment]
I've made AuthMe backward compatible in last commits, I will not remove 1.6.4 support cause lot of server work on due to Spout or other kind of Mods

**Comment by sgdc3** [comment]
I will check on mcstats ;)

**Comment by sgdc3** [comment]
@Xephi , in the meantime you can safely mergge this pr, it doesn't remove spout ;)

**Comment by sgdc3** [comment]
I forgot authme haven't metrics xD

**Comment by sgdc3** [comment]
Ok, all maven issues fixed ;)

**Comment by sgdc3** [comment]
Bump

**Comment by sgdc3** [comment]
Thanks ;)

**Comment by Xephi** [comment]
Thanks to you ;)

**Pull request merged**
