### PR TITLE
Add more password error messages

### LINKED ISSUE #94: /REG and /ChangePassword bug??
I am using the lastest dev version and thats #17,i am just using a testing server,when the plugin tolds me to register,i used /reg WaterXCubic WaterXCubic and thats my username,i used tab to get it,it says they are not the same,i manully type it myself,and it also said that

However,i used /reg 123456 123456 and it worked fine

### PR DESCRIPTION
**Pull request by sgdc3**

### CODE REVIEW

**Comment by sgdc3** [comment]
Should fix #94

**Comment by sgdc3** [comment]
Lol, never edit java with github editor xD

**Comment by Xephi** [comment]
You need to add them in each message_x.yml files ( you can add them in english in the first time :'))

**Comment by sgdc3** [comment]
@Xephi done ;)

**Pull request merged**
