### PR TITLE
Fixed Problem with Dependencies conflict

### PR DESCRIPTION
**Pull request by sgdc3**

### CODE REVIEW

**Comment by sgdc3** [comment]
Ups I think this may not work! Waiting for travis result

**Comment by Xephi** [comment]
Why don't use the official Essentials repo ?
http://repo.ess3.net/content/groups/public

**Comment by sgdc3** [comment]
Because Essentials is outdated, EssentialsX have a lots of fix and enhancements.

**Comment by Xephi** [comment]
We only need the api to compile with, is it really important? >.<

**Comment by Xephi** [comment]
Build Success when change from EssentialsX to Essentials ^^"

**Comment by sgdc3** [comment]
I didn't check if they have fixed issues about the API

**Comment by sgdc3** [comment]
Ok, i will check if there are differences in the API

**Comment by sgdc3** [comment]
You're right, if there aren't issues it's useless.

**Pull request closed without merging**
