### PR TITLE
Updated to JDK 8

### PR DESCRIPTION
**Pull request by sgdc3**

### CODE REVIEW

**Comment by Maxetto** [comment]
Oh noes, I disagree! 70% of Minecraft servers are still in JDK 7 (mine too)!

I already saw a plugin updating to JDK 8 and, beside it had 10k downloads, it got hundreds of complains.

**Comment by sgdc3** [comment]
@Maxetto Il plugin non va più su java 7, se vai a vedere i commenti e gli avvertimenti di Xephi

**Comment by Trojaner25** [comment]
Its sadly true, that about 70% of the servers use Java 1.8: http://mcstats.org/plugin/Spigot

I see no reason why you should update to Java 1.8...

**Comment by Xephi** [comment]
I will try to compile it under jdk7

**Pull request closed without merging**
