### PR TITLE
Translate to Japanese

### PR DESCRIPTION
**Pull request by katabamia**
Hello AuthMeReloaded team.
I translated `messages_en.yml` to Japanese.

I hope to this plugin supported UTF-8 encoding and Multi-byte char.

If I made any problem, please tell me. I'll fix it.

thanks,

### CODE REVIEW

**Comment by katabamia** [comment]
P.S.  if Japanese person looking this PR and found any miss translate, please tell me!

**Comment by DNx5** [comment]
Hi @katabamia ,
 Thank you for the translation, it's looks good for me.

**Comment by DNx5** [comment]
oops, it's on the wrong repo :laughing:

**Comment by sgdc3** [comment]
Merged by @DNx5 into the development repo

**Comment by katabamia** [comment]
@DNx5 @sgdc3 Thanks to marge! but I'm sorry to I requested to wrong repo 😨

**Comment by ljacqu** [comment]
@katabamia No problem! Thank you for providing a Japanese translation :)

**Pull request merged**
