### PR TITLE
[DO NOT MERGE] Stuff from DEV repo in realtime

### PR DESCRIPTION
**Pull request by Xephi**

### CODE REVIEW

**Comment by sgdc3** [comment]
@Xephi We can add a removeGamemodeOnQuit feature

**Comment by Xephi** [comment]
I will merge that when we'll prepare to release :p

**Comment by sgdc3** [comment]
@Xephi @ljacqu @games647 @DNx5 Should we merge this?

**Comment by ljacqu** [comment]
@sgdc3 I suggest we make a release soon. No matter what's still open the plugin is usable and we have to answer "use a dev build" often to people opening issues because this old 5.0 version was downloaded from the Bukkit page.

**Comment by sgdc3** [comment]
@ljacqu I've added a SNAPSHOT build to the bukkit page.

**Comment by ljacqu** [comment]
@sgdc3 Oh, that's awesome! Thanks for doing that

**Comment by sgdc3** [comment]
deleted the jar due tu unsolved critical bugs

**Pull request merged**
