### PR TITLE
Removed ChestShop hook (moved)

### PR DESCRIPTION
**Pull request by sgdc3**

### CODE REVIEW

**Comment by Xephi** [comment]
Why ? :O

**Comment by sgdc3** [comment]
https://github.com/Acrobot/ChestShop-3/pull/43

**Comment by sgdc3** [comment]
Can you contact me on gitter? @Xephi

**Comment by sgdc3** [comment]
@Xephi

**Comment by sgdc3** [comment]
@Xephi

**Comment by Xephi** [comment]
Deprecate it if you want, but don't remove it ... if people use oldest version it will broke the hook :O

**Comment by sgdc3** [comment]
At least set it to false as default and rename the option to
"legacyChestshop"
Il 09/ago/2015 11:31 PM, "Alexandre Vanhecke" <notifications@github.com> ha
scritto:

**Comment by sgdc3** [comment]
@Xephi

**Pull request closed without merging**
